# Generated by Django 5.1.2 on 2024-11-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_country_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='defautly_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='county',
            new_name='defautly_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='defautly_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postcode',
            new_name='defautly_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address1',
            new_name='defautly_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address2',
            new_name='defautly_street_address2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='town_or_city',
            new_name='defautly_town_or_city',
        ),
    ]
