# Generated by Django 5.1.2 on 2024-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productreview_half_star_productreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
